weekDir = ../../
toCopy = $(weekDir){download_movielens.sh,movielens.R}
$(wildcard .\{download_movielens.sh,movielens.R}): $(wildcard toCopy)
	co $(toCopy) ./
#rivatropp@gmail.com
#hackerank
#glassdoor
#indeed