weekDir = ../../
initialSetUp = ../../@(download_movielens.sh|movielens.Rmd);
objects=main1.o foo.o main2.o bar.objects

loadSetup: $(wildcard initialSetup)
	echo $(wildcard initialSetup)
	echo $(objects)
targetFiles = [
	../../download_movielens.sh,
	../../movielens.Rmd
]
#rivatropp@gmail.com
#hackerank
#glassdoor
#indeed
